export interface BarangayOption {
  code: string;
  name: string;
}

// All 48 barangays of Tanauan City, Batangas
export const BARANGAYS: BarangayOption[] = [
  { code: 'BGY-ABAT-001', name: 'Altura Bata' },
  { code: 'BGY-AMAT-002', name: 'Altura Matanda' },
  { code: 'BGY-AMBU-003', name: 'Ambulong' },
  { code: 'BGY-BAGB-004', name: 'Bagbag' },
  { code: 'BGY-BAGY-005', name: 'Bagumbayan' },
  { code: 'BGY-BALE-006', name: 'Balele' },
  { code: 'BGY-BEAS-007', name: 'Banjo East' },
  { code: 'BGY-BLAU-008', name: 'Banjo Laurel' },
  { code: 'BGY-BILO-009', name: 'Bilog-Bilog' },
  { code: 'BGY-BOOT-010', name: 'Boot' },
  { code: 'BGY-CALE-011', name: 'Cale' },
  { code: 'BGY-DARA-012', name: 'Darasa' },
  { code: 'BGY-GONZ-013', name: 'Gonzales' },
  { code: 'BGY-HIDA-014', name: 'Hidalgo' },
  { code: 'BGY-JANO-015', name: 'Janopol' },
  { code: 'BGY-JORI-016', name: 'Janopol Oriental' },
  { code: 'BGY-LAUR-017', name: 'Laurel' },
  { code: 'BGY-LUYO-018', name: 'Luyos' },
  { code: 'BGY-MABI-019', name: 'Mabini' },
  { code: 'BGY-MPUL-020', name: 'Malaking Pulo' },
  { code: 'BGY-MPAZ-021', name: 'Maria Paz' },
  { code: 'BGY-MAUG-022', name: 'Maugat' },
  { code: 'BGY-MONT-023', name: 'Montana' },
  { code: 'BGY-NATA-024', name: 'Natatas' },
  { code: 'BGY-PGAR-025', name: 'Padre Garcia' },
  { code: 'BGY-PAIB-026', name: 'Payapa Ibaba' },
  { code: 'BGY-PAIL-027', name: 'Payapa Ilaya' },
  { code: 'BGY-POB1-028', name: 'Poblacion Barangay 1' },
  { code: 'BGY-POB2-029', name: 'Poblacion Barangay 2' },
  { code: 'BGY-POB3-030', name: 'Poblacion Barangay 3' },
  { code: 'BGY-POB4-031', name: 'Poblacion Barangay 4' },
  { code: 'BGY-POB5-032', name: 'Poblacion Barangay 5' },
  { code: 'BGY-POB6-033', name: 'Poblacion Barangay 6' },
  { code: 'BGY-POB7-034', name: 'Poblacion Barangay 7' },
  { code: 'BGY-SALA-035', name: 'Sala' },
  { code: 'BGY-SAMB-036', name: 'Sambat' },
  { code: 'BGY-SJOS-037', name: 'San Jose' },
  { code: 'BGY-SNTL-038', name: 'Santol' },
  { code: 'BGY-SNTR-039', name: 'Santor' },
  { code: 'BGY-SULP-040', name: 'Sulpoc' },
  { code: 'BGY-SUPL-041', name: 'Suplang' },
  { code: 'BGY-TALA-042', name: 'Talaga' },
  { code: 'BGY-TALI-043', name: 'Talisay' },
  { code: 'BGY-TINU-044', name: 'Tinurik' },
  { code: 'BGY-TRAP-045', name: 'Trapiche' },
  { code: 'BGY-ULAN-046', name: 'Ulango' },
  { code: 'BGY-WAWA-047', name: 'Wawa' },
];
